// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HIME_EquipSlotsCore","status":true,"description":"v1.5 - Provides you with tools to set up custom equip slots\r\nfor each actor individually.","parameters":{}},
{"name":"HIME_SideviewActorEnemies","status":true,"description":"v1.2 - Allows you to use side-view actors as enemies.","parameters":{}},
{"name":"HIME_EnemyEquips","status":true,"description":"v1.3 - Allows you to give enemies equips. Provides\r\nfunctionality for managing enemy equips.","parameters":{}},
{"name":"HIME_SideviewActorEnemyWeapons","status":true,"description":"v1.2 - This is an add-on for Sideview Actor Enemies that allows\r\nyou to display enemy weapons and enemy weapon animations.","parameters":{}}
];
